### PR TITLE
Raf 253 tree lib

### PR DESCRIPTION
**Pull request by HodaAlemi**
Please review the binary search tree library.

### CODE REVIEW

**Comment by natbusa** [comment]
What was wrong with SortedSet?
http://www.scala-lang.org/api/2.11.4/index.html#scala.collection.SortedSet

**Comment by HodaAlemi** [comment]
Sets do not have duplicate values, we need to keep duplicates.

**Comment by natbusa** [comment]
If you need to count keys and have the keys sorted, there are already data structures for that.

just keys:
http://www.scala-lang.org/api/2.11.4/index.html#scala.collection.immutable.TreeSet

keys and values
http://www.scala-lang.org/api/2.11.4/index.html#scala.collection.immutable.TreeMap

furthermore many data structures in scala have a method called "Sorted".
It sorts the data structure according to a given Ordering.

**Comment by HodaAlemi** [comment]
We need a sorted list. However, we do not use a List structure, as by inserting a new value in the sorted list, the ordering time will be higher (O(n)) than using a binary search tree (O(log n)).

**Comment by natbusa** [comment]
That's exactly why you can use the tree map/set for that.

**Pull request merged**
