### PR TITLE
Raf 324: Json actor

### PR DESCRIPTION
**Pull request by gvr**
The following design choices have been made for this iteration:
1. When template references are not found in the input Json the field is set to null
2. references are marked by having a colon (:) as first character
3. The template is not yet validated (except implicit verification that it is valid json): expression syntax would be nice to have been checked before creating an actor, but it would be best to have a facility for that in the JsonExpressionParser

### CODE REVIEW

**Comment by Digibeet** [comment]
The ':' Notation for expressions is, in my always humble oppinion, very easy to miss when you read the code. I would prefer expressions to be identified with double accolades like {{EXPRESSION}}.

**Comment by natbusa** [comment]
curly braces interfere with json ...
what about $variable?

**Comment by gvr** [comment]
Curly braces wouldn't interfere as the expression would still need to be a json string ("{{ ... some expression ... }}"), and they indeed do have more of an in-your-face quality than the modest colon.
The dollar variable for an expression would also be for an expression probably more elegantly indicated with surrounding braces ("${... some expression ...}").
These constructions might however hint that "average is ${expression1} and sd is ${expression2}" are possible constructions, which is not the case (expressions may return other types than strings). This is why I would prefer some prefix notation.
I'll however happily leave a decision up to the aesthetics committee.

**Comment by natbusa** [comment]
After some more thinking this is my humble proposal:

1) we need to maintain valid json
2) we need to have a mechanism to switch context where expression are
evaluated rather then interpreted as strings

what we could do is to do that as a global value syntax context switch.

let me explain myself
if we find

"jsonfield" : "some text literal here"

the value is a string

if we find

"jsonfield" : "${ trigger.city }"

trigger.city is parsed from the variable trigger with json path accessing
the field city

in this way we need only to check for
"${  as open delimiter for the expr context and  }" for the closing
delimiter

In the unlikely case that a use wants a string literal starting with ${ and
ending with }" then it must be escaped as /$. further leading / in a string
literal must be doubled up for escaping.

a value wide context switch will allow us in the future to do things like

"jsonfield" : "${ trigger.checkins + 1}"
or
"jsonfield" : "${ trigger.amount > 23}"

since the expression parser is going from json to json, it makes sense to
me to interpret/parse it as a proper subset of the javascript grammar. (by
defining our json access via json path we are actually already complying
herewidth)

**Comment by natbusa** [comment]
the main difference between my proposal and Gers is that in his solution
there is an implicit concatenation of strings, which requires the
expression to be necesarily recasted as string. so I would not go there but
in fact fold it as follow.

mutatis mutandis:

"jsonfield" : "${'the city is ' + trigger.city }"

**Comment by gvr** [comment]
The ${ ... } construct is adopted as identifier for expressions

**Pull request merged**
